# Streamlit Cloud Secrets Configuration
# Set your real API keys in Streamlit Cloud dashboard under "Secrets"

OPENAI_API_KEY = "your-openai-api-key-here"
LANGSMITH_API_KEY = "your-langsmith-api-key-here" 
LANGSMITH_ASSISTANT_ID = "your-assistant-id-here"
LANGSMITH_DEPLOYMENT = "Green Hill Canarias Digital Twin"
LANGCHAIN_API_KEY = "your-langchain-api-key-here"